### ISSUE TITLE
Updating user LCC seems to not be working

### ISSUE THREAD

**Issue by fenwaypowers** [CIF-Rochester/GateKeeper#10]
```
[2024-04-14 20:15:29] INFO     LCC of user japple is 11. Swiped LCC was 12. Updating user japple with new LCC of 12...
[2024-04-14 20:15:29] WARNING  The attempt to change the LCC of user japple from 11 to 12 failed.
[2024-04-14 20:15:29] ERROR    Insufficient access: Insufficient 'write' privilege to the 'employeeType' attribute of entry 'uid=stsegai,cn=users,cn=accounts,dc=cif,dc=rochester,dc=edu'.
Traceback (most recent call last):
  File "/XXX/account.py", line 76, in has_access
    self.update_LCC()
  File "/XXX/account.py", line 92, in update_LCC
    self.client.user_mod(a_uid=self.netid, o_employeetype=self.swiped_lcc)
  File "/XXX/.venv/lib/python3.8/site-packages/python_freeipa/client_meta.py", line 26376, in user_mod
    return self._request(method, _args, _params)
  File "/XXX/.venv/lib/python3.8/site-packages/python_freeipa/client.py", line 335, in _request
    parse_error(error)
  File "/XXX/.venv/lib/python3.8/site-packages/python_freeipa/exceptions.py", line 117, in parse_error
    raise exception_class(message, code)
python_freeipa.exceptions.Denied: Insufficient access: Insufficient 'write' privilege to the 'employeeType' attribute of entry 'uid=stsegai,cn=users,cn=accounts,dc=cif,dc=rochester,dc=edu'.
[2024-04-14 20:15:29] INFO     Access granted to japple 
[2024-04-14 20:15:29] INFO     RasPi Striking!
```

it said the attempt to change the lcc number failed, but then on his second swipe japple had access.
these exact log messages have happened before as well when japple has tried to swipe into the lab.

**Comment by fenwaypowers** [comment]
the `admin` role has been transferred to the `gatekeeper` account.
hopefully this will fix the issue.

**Comment by fenwaypowers** [comment]
updating `gatekeeper` account perms fixed the issue.

**Comment by fenwaypowers** [comment]
updating `gatekeeper` account perms fixed the issue.
